# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Work_QT\CAN_USB\formcantx.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FormCanTx(object):
    def setupUi(self, FormCanTx):
        FormCanTx.setObjectName("FormCanTx")
        FormCanTx.resize(888, 50)
        FormCanTx.setMinimumSize(QtCore.QSize(0, 40))
        FormCanTx.setMaximumSize(QtCore.QSize(16777215, 50))
        self.verticalLayout = QtWidgets.QVBoxLayout(FormCanTx)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.chEnable = QtWidgets.QCheckBox(FormCanTx)
        self.chEnable.setMinimumSize(QtCore.QSize(10, 24))
        self.chEnable.setMaximumSize(QtCore.QSize(20, 32))
        self.chEnable.setText("")
        self.chEnable.setObjectName("chEnable")
        self.horizontalLayout_2.addWidget(self.chEnable)
        self.leId = QtWidgets.QLineEdit(FormCanTx)
        self.leId.setMinimumSize(QtCore.QSize(40, 24))
        self.leId.setMaximumSize(QtCore.QSize(80, 32))
        self.leId.setAlignment(QtCore.Qt.AlignCenter)
        self.leId.setObjectName("leId")
        self.horizontalLayout_2.addWidget(self.leId)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leData0 = QtWidgets.QLineEdit(FormCanTx)
        self.leData0.setMinimumSize(QtCore.QSize(20, 24))
        self.leData0.setMaximumSize(QtCore.QSize(30, 32))
        self.leData0.setAlignment(QtCore.Qt.AlignCenter)
        self.leData0.setObjectName("leData0")
        self.horizontalLayout.addWidget(self.leData0)
        self.leData1 = QtWidgets.QLineEdit(FormCanTx)
        self.leData1.setMinimumSize(QtCore.QSize(20, 24))
        self.leData1.setMaximumSize(QtCore.QSize(30, 32))
        self.leData1.setAlignment(QtCore.Qt.AlignCenter)
        self.leData1.setObjectName("leData1")
        self.horizontalLayout.addWidget(self.leData1)
        self.leData2 = QtWidgets.QLineEdit(FormCanTx)
        self.leData2.setMinimumSize(QtCore.QSize(20, 24))
        self.leData2.setMaximumSize(QtCore.QSize(30, 32))
        self.leData2.setAlignment(QtCore.Qt.AlignCenter)
        self.leData2.setObjectName("leData2")
        self.horizontalLayout.addWidget(self.leData2)
        self.leData3 = QtWidgets.QLineEdit(FormCanTx)
        self.leData3.setMinimumSize(QtCore.QSize(20, 24))
        self.leData3.setMaximumSize(QtCore.QSize(30, 32))
        self.leData3.setAlignment(QtCore.Qt.AlignCenter)
        self.leData3.setObjectName("leData3")
        self.horizontalLayout.addWidget(self.leData3)
        self.leData4 = QtWidgets.QLineEdit(FormCanTx)
        self.leData4.setMinimumSize(QtCore.QSize(20, 24))
        self.leData4.setMaximumSize(QtCore.QSize(30, 32))
        self.leData4.setAlignment(QtCore.Qt.AlignCenter)
        self.leData4.setObjectName("leData4")
        self.horizontalLayout.addWidget(self.leData4)
        self.leData5 = QtWidgets.QLineEdit(FormCanTx)
        self.leData5.setMinimumSize(QtCore.QSize(20, 24))
        self.leData5.setMaximumSize(QtCore.QSize(30, 32))
        self.leData5.setAlignment(QtCore.Qt.AlignCenter)
        self.leData5.setObjectName("leData5")
        self.horizontalLayout.addWidget(self.leData5)
        self.leData6 = QtWidgets.QLineEdit(FormCanTx)
        self.leData6.setMinimumSize(QtCore.QSize(20, 24))
        self.leData6.setMaximumSize(QtCore.QSize(30, 32))
        self.leData6.setAlignment(QtCore.Qt.AlignCenter)
        self.leData6.setObjectName("leData6")
        self.horizontalLayout.addWidget(self.leData6)
        self.leData7 = QtWidgets.QLineEdit(FormCanTx)
        self.leData7.setMinimumSize(QtCore.QSize(20, 24))
        self.leData7.setMaximumSize(QtCore.QSize(30, 32))
        self.leData7.setAlignment(QtCore.Qt.AlignCenter)
        self.leData7.setObjectName("leData7")
        self.horizontalLayout.addWidget(self.leData7)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.leLength = QtWidgets.QLineEdit(FormCanTx)
        self.leLength.setMinimumSize(QtCore.QSize(20, 24))
        self.leLength.setMaximumSize(QtCore.QSize(30, 32))
        self.leLength.setAlignment(QtCore.Qt.AlignCenter)
        self.leLength.setObjectName("leLength")
        self.horizontalLayout_2.addWidget(self.leLength)
        self.cbFormat = QtWidgets.QComboBox(FormCanTx)
        self.cbFormat.setMinimumSize(QtCore.QSize(40, 24))
        self.cbFormat.setMaximumSize(QtCore.QSize(60, 32))
        self.cbFormat.setObjectName("cbFormat")
        self.horizontalLayout_2.addWidget(self.cbFormat)
        self.cbType = QtWidgets.QComboBox(FormCanTx)
        self.cbType.setMinimumSize(QtCore.QSize(60, 24))
        self.cbType.setMaximumSize(QtCore.QSize(70, 24))
        self.cbType.setObjectName("cbType")
        self.horizontalLayout_2.addWidget(self.cbType)
        self.btnSend = QtWidgets.QPushButton(FormCanTx)
        self.btnSend.setMinimumSize(QtCore.QSize(40, 24))
        self.btnSend.setMaximumSize(QtCore.QSize(40, 32))
        self.btnSend.setObjectName("btnSend")
        self.horizontalLayout_2.addWidget(self.btnSend)
        self.btnDelete = QtWidgets.QPushButton(FormCanTx)
        self.btnDelete.setMinimumSize(QtCore.QSize(40, 24))
        self.btnDelete.setMaximumSize(QtCore.QSize(40, 32))
        self.btnDelete.setObjectName("btnDelete")
        self.horizontalLayout_2.addWidget(self.btnDelete)
        self.checkBox = QtWidgets.QCheckBox(FormCanTx)
        self.checkBox.setMinimumSize(QtCore.QSize(40, 24))
        self.checkBox.setMaximumSize(QtCore.QSize(40, 24))
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_2.addWidget(self.checkBox)
        self.sbInterval = QtWidgets.QSpinBox(FormCanTx)
        self.sbInterval.setMinimumSize(QtCore.QSize(70, 24))
        self.sbInterval.setMaximumSize(QtCore.QSize(70, 24))
        self.sbInterval.setMinimum(0)
        self.sbInterval.setMaximum(10000)
        self.sbInterval.setSingleStep(100)
        self.sbInterval.setProperty("value", 100)
        self.sbInterval.setObjectName("sbInterval")
        self.horizontalLayout_2.addWidget(self.sbInterval)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(FormCanTx)
        QtCore.QMetaObject.connectSlotsByName(FormCanTx)

    def retranslateUi(self, FormCanTx):
        _translate = QtCore.QCoreApplication.translate
        FormCanTx.setWindowTitle(_translate("FormCanTx", "Form"))
        self.leId.setInputMask(_translate("FormCanTx", "HHHHHHHH"))
        self.leId.setText(_translate("FormCanTx", "00000000"))
        self.leData0.setInputMask(_translate("FormCanTx", "HH"))
        self.leData0.setText(_translate("FormCanTx", "00"))
        self.leData1.setInputMask(_translate("FormCanTx", "HH"))
        self.leData1.setText(_translate("FormCanTx", "00"))
        self.leData2.setInputMask(_translate("FormCanTx", "HH"))
        self.leData2.setText(_translate("FormCanTx", "00"))
        self.leData3.setInputMask(_translate("FormCanTx", "HH"))
        self.leData3.setText(_translate("FormCanTx", "00"))
        self.leData4.setInputMask(_translate("FormCanTx", "HH"))
        self.leData4.setText(_translate("FormCanTx", "00"))
        self.leData5.setInputMask(_translate("FormCanTx", "HH"))
        self.leData5.setText(_translate("FormCanTx", "00"))
        self.leData6.setInputMask(_translate("FormCanTx", "HH"))
        self.leData6.setText(_translate("FormCanTx", "00"))
        self.leData7.setInputMask(_translate("FormCanTx", "HH"))
        self.leData7.setText(_translate("FormCanTx", "00"))
        self.leLength.setInputMask(_translate("FormCanTx", "HH"))
        self.leLength.setText(_translate("FormCanTx", "08"))
        self.btnSend.setText(_translate("FormCanTx", "TX"))
        self.btnDelete.setText(_translate("FormCanTx", "DEL"))
        self.checkBox.setText(_translate("FormCanTx", "ms"))

