# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Work_QT\CAN_USB\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 820)
        MainWindow.setMaximumSize(QtCore.QSize(1000, 1400))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setMinimumSize(QtCore.QSize(50, 24))
        self.label_3.setMaximumSize(QtCore.QSize(60, 32))
        self.label_3.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.btnConnect = QtWidgets.QPushButton(self.centralWidget)
        self.btnConnect.setMinimumSize(QtCore.QSize(60, 24))
        self.btnConnect.setMaximumSize(QtCore.QSize(140, 32))
        self.btnConnect.setObjectName("btnConnect")
        self.horizontalLayout.addWidget(self.btnConnect)
        self.cbComBaud = QtWidgets.QComboBox(self.centralWidget)
        self.cbComBaud.setMinimumSize(QtCore.QSize(60, 24))
        self.cbComBaud.setMaximumSize(QtCore.QSize(140, 32))
        self.cbComBaud.setObjectName("cbComBaud")
        self.horizontalLayout.addWidget(self.cbComBaud)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setMinimumSize(QtCore.QSize(100, 24))
        self.label_2.setMaximumSize(QtCore.QSize(140, 32))
        self.label_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.btnCanGetBaudRate = QtWidgets.QPushButton(self.centralWidget)
        self.btnCanGetBaudRate.setMinimumSize(QtCore.QSize(50, 24))
        self.btnCanGetBaudRate.setMaximumSize(QtCore.QSize(70, 32))
        self.btnCanGetBaudRate.setObjectName("btnCanGetBaudRate")
        self.horizontalLayout_2.addWidget(self.btnCanGetBaudRate)
        self.leBaudrate = QtWidgets.QLineEdit(self.centralWidget)
        self.leBaudrate.setMinimumSize(QtCore.QSize(60, 24))
        self.leBaudrate.setMaximumSize(QtCore.QSize(100, 32))
        self.leBaudrate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.leBaudrate.setObjectName("leBaudrate")
        self.horizontalLayout_2.addWidget(self.leBaudrate)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.btnCanBaudRate = QtWidgets.QPushButton(self.centralWidget)
        self.btnCanBaudRate.setMinimumSize(QtCore.QSize(50, 24))
        self.btnCanBaudRate.setMaximumSize(QtCore.QSize(70, 32))
        self.btnCanBaudRate.setObjectName("btnCanBaudRate")
        self.horizontalLayout_3.addWidget(self.btnCanBaudRate)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.frameTx = QtWidgets.QFrame(self.centralWidget)
        self.frameTx.setMinimumSize(QtCore.QSize(100, 0))
        self.frameTx.setMaximumSize(QtCore.QSize(16777215, 300))
        self.frameTx.setFrameShape(QtWidgets.QFrame.Panel)
        self.frameTx.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTx.setObjectName("frameTx")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frameTx)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.frameTx)
        self.label_4.setMinimumSize(QtCore.QSize(100, 24))
        self.label_4.setMaximumSize(QtCore.QSize(140, 32))
        self.label_4.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.btnAddTx = QtWidgets.QPushButton(self.frameTx)
        self.btnAddTx.setMinimumSize(QtCore.QSize(50, 24))
        self.btnAddTx.setMaximumSize(QtCore.QSize(80, 32))
        self.btnAddTx.setSizeIncrement(QtCore.QSize(0, 0))
        self.btnAddTx.setObjectName("btnAddTx")
        self.horizontalLayout_4.addWidget(self.btnAddTx)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.btnSaveTx = QtWidgets.QPushButton(self.frameTx)
        self.btnSaveTx.setMinimumSize(QtCore.QSize(50, 24))
        self.btnSaveTx.setMaximumSize(QtCore.QSize(80, 32))
        self.btnSaveTx.setSizeIncrement(QtCore.QSize(0, 0))
        self.btnSaveTx.setObjectName("btnSaveTx")
        self.horizontalLayout_4.addWidget(self.btnSaveTx)
        self.btnLoadTx = QtWidgets.QPushButton(self.frameTx)
        self.btnLoadTx.setMinimumSize(QtCore.QSize(50, 24))
        self.btnLoadTx.setMaximumSize(QtCore.QSize(80, 32))
        self.btnLoadTx.setSizeIncrement(QtCore.QSize(0, 0))
        self.btnLoadTx.setObjectName("btnLoadTx")
        self.horizontalLayout_4.addWidget(self.btnLoadTx)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.listTx = QtWidgets.QListWidget(self.frameTx)
        self.listTx.setObjectName("listTx")
        self.verticalLayout_2.addWidget(self.listTx)
        self.verticalLayout_3.addWidget(self.frameTx)
        self.frameRx = QtWidgets.QFrame(self.centralWidget)
        self.frameRx.setMinimumSize(QtCore.QSize(0, 400))
        self.frameRx.setMaximumSize(QtCore.QSize(1000, 900))
        self.frameRx.setFrameShape(QtWidgets.QFrame.Panel)
        self.frameRx.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameRx.setLineWidth(2)
        self.frameRx.setObjectName("frameRx")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frameRx)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.frameRx)
        self.label_5.setMinimumSize(QtCore.QSize(100, 24))
        self.label_5.setMaximumSize(QtCore.QSize(140, 32))
        self.label_5.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.btnRxClear = QtWidgets.QPushButton(self.frameRx)
        self.btnRxClear.setMinimumSize(QtCore.QSize(50, 24))
        self.btnRxClear.setMaximumSize(QtCore.QSize(80, 32))
        self.btnRxClear.setSizeIncrement(QtCore.QSize(0, 0))
        self.btnRxClear.setObjectName("btnRxClear")
        self.horizontalLayout_5.addWidget(self.btnRxClear)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.btnSaveRx = QtWidgets.QPushButton(self.frameRx)
        self.btnSaveRx.setMinimumSize(QtCore.QSize(50, 24))
        self.btnSaveRx.setMaximumSize(QtCore.QSize(80, 32))
        self.btnSaveRx.setSizeIncrement(QtCore.QSize(0, 0))
        self.btnSaveRx.setObjectName("btnSaveRx")
        self.horizontalLayout_5.addWidget(self.btnSaveRx)
        self.btnLoadRx = QtWidgets.QPushButton(self.frameRx)
        self.btnLoadRx.setMinimumSize(QtCore.QSize(50, 24))
        self.btnLoadRx.setMaximumSize(QtCore.QSize(80, 32))
        self.btnLoadRx.setSizeIncrement(QtCore.QSize(0, 0))
        self.btnLoadRx.setObjectName("btnLoadRx")
        self.horizontalLayout_5.addWidget(self.btnLoadRx)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.twRx = QtWidgets.QTableWidget(self.frameRx)
        self.twRx.setColumnCount(0)
        self.twRx.setObjectName("twRx")
        self.twRx.setRowCount(0)
        self.twRx.horizontalHeader().setDefaultSectionSize(60)
        self.twRx.horizontalHeader().setMinimumSectionSize(20)
        self.twRx.horizontalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.twRx)
        self.verticalLayout_3.addWidget(self.frameRx)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 900, 26))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "USB-CAN Tool"))
        self.label_3.setText(_translate("MainWindow", "USB"))
        self.btnConnect.setText(_translate("MainWindow", "CONNECT"))
        self.label_2.setText(_translate("MainWindow", "CAN BAUDRATE"))
        self.btnCanGetBaudRate.setText(_translate("MainWindow", "GET"))
        self.leBaudrate.setInputMask(_translate("MainWindow", "9999999"))
        self.leBaudrate.setText(_translate("MainWindow", "500000"))
        self.btnCanBaudRate.setText(_translate("MainWindow", "SET"))
        self.label_4.setText(_translate("MainWindow", "CAN TX"))
        self.btnAddTx.setText(_translate("MainWindow", "ADD"))
        self.btnSaveTx.setText(_translate("MainWindow", "SAVE"))
        self.btnLoadTx.setText(_translate("MainWindow", "LOAD"))
        self.label_5.setText(_translate("MainWindow", "CAN RX"))
        self.btnRxClear.setText(_translate("MainWindow", "CLEAR"))
        self.btnSaveRx.setText(_translate("MainWindow", "SAVE"))
        self.btnLoadRx.setText(_translate("MainWindow", "LOAD"))

